### ISSUE TITLE
Plugin not working?

### ISSUE THREAD

**Issue by neographikal** [SenTzu01/pimatic-telegram#1]
I've followed the instructions, got the token, went to api.telegram.com/botX/getUpdates and got the id of myself and added the settings to the configuration. Added a rule to test, I see that the rule is executed but I do not receive any messages. Also tried to add myself to the extra receipients list with a username and chatid but still no sigar.

```
{
      "plugin": "telegram",
      "active": true,
      "host": "api.telegram.org",
      "apiToken": "111111:AAHHAAAAAAAAAAAAAAAAAAAAAAAAA",
      "userChatId": "11111111",
      "recipients": [
        {
          "name": "@neographikal",
          "userChatId": "11111111",
          "enabled": true
        }
      ]
    },
```

I don't see any errors in the log. I'm on version 1.0.2.

**Comment by SenTzu01** [comment]
Hi,
Have you restarted Pimatic after adding the entry to the recipient list? this is required for Pimatic to reload the config changes

**Comment by neographikal** [comment]
And now it's working, thought I already restarted it. I did change the config: 

```
"plugin": "telegram",
      "active": true,
```

was below the receipients, maybe that made a difference. Thanks for the great plugin!
