### ISSUE TITLE
TelegramReceiverDevice syntax in config.json

### ISSUE THREAD

**Issue by mocart2** [SenTzu01/pimatic-telegram#10]
Hi!
I can't create **TelegramReceiverDevice**, can anybody help me with syntax (ex.):
```
{
"id": "TelegramReceiverDevice",
"name": "TelegramReceiverDevice",
"class": "TelegramReceiverDevice"
}
```
where is my mistake?

**Comment by SenTzu01** [comment]
This question is being handled on the Pimatic forum: https://forum.pimatic.org/topic/2616/new-plugin-for-telegram
