### ISSUE TITLE
Bot sends old values 

### ISSUE THREAD

**Issue by ccvh** [SenTzu01/pimatic-telegram#16]
I've created the following rule to get the recent temperature of two sensors:
"When telegram received "temperatur" then send text telegram to Chris "Wohnzimmer: $wohnzimmer-sensor.temperature, Balkon: $balkon-sensor.temperature""

When i now send "temperature" to my telegram bot it always sends me old values (exactly those, which were true, when i created the rule). It seems like the rule is not refreshing the variables?

**Comment by SenTzu01** [comment]
Hi Chris,
Thanks for reporting the issue. Rule parsing is completely left to the Pimatic core, my assumption was and is the plugin just needs to receive the parsed output. I'll try to reproduce and check if I can see if the vars are indeed parsed just-in-time or if additional steps are needed. Else I'll content mwittig for this.

**Comment by SenTzu01** [comment]
Chris, I have been able to reproduce your scenario. Adding it as a bug. Will fix in next release.

**Comment by ccvh** [comment]
Thanks for your effort! Really nice work, keep it up!

**Comment by SenTzu01** [comment]
Added to dev branch, will be merged into next release
