### ISSUE TITLE
sendDocument

### ISSUE THREAD

**Issue by andi216** [SenTzu01/pimatic-telegram#22]
Hello! 
You can implement and sending documents?
Now to send a (.txt) file using a rule very long.
execute “curl -s -X POST https://api.telegram.org/botXXXX:YYYYYYYYYY/sendDocument -F chat_id=ZZZZZ -F document=@/home/pi/ips/ips.txt”
Thank you in advance.

**Comment by SenTzu01** [comment]
Yes, I will implement, have implemented locally just now. Will add some further checking on files (access / size) before pushing to release
