### ISSUE TITLE
[Feature Request] Reading values from messages received

### ISSUE THREAD

**Issue by ccvh** [SenTzu01/pimatic-telegram#26]
Not sure if possible, probably need something like regular expression in rules (pimatic-related problem, not your plugin maybe)?

The thing i'd like to have is: When sending the bot a message with "Temperatur Wohnzimmer 25" it should "read" the 25 and set the thermostat value to 25; if messaged with 18, it should set it to 18, etc. 
If not possible: Forget about it, then i'll create a rule for each let's say 3-4 common temperatures and room.

**Comment by SenTzu01** [comment]
@ccvh This is pimatic related. Telegram has a messaging responsibility, and can be used to control rules and devices. What you are after is a core function in the rule system. If not clear on how to achieve, I am sure the folks on the forum are ready to help out!

**Comment by SenTzu01** [comment]
Implemented with Feature request #35
