### ISSUE TITLE
Bot commands

### ISSUE THREAD

**Issue by rikki78** [SenTzu01/pimatic-telegram#28]
Hello,

A while ago I've added some commands to the plugin, starting with a /. The benefit for me is that it is easy to type as my bot knows these commands and I get a list of commands to choose from. 
Now I've noticed it isn't possible to use these anymore as I get a message "Bot commands (/<cmd>) are not implemented". 
Is there a special reason to exclude these? It worked fine before.
thanks

**Comment by SenTzu01** [comment]
In an earlier version this was indeed possible, albeit an undocumented feature. At the time I decided to reserve the use of / commands for future enhancements.
When defining commands (predicates) in the rule engine, you can also obtain a list of available predicates by executing "help"
