### ISSUE TITLE
Send message only to one recipient.

### ISSUE THREAD

**Issue by zjuanma** [SenTzu01/pimatic-telegram#29]
I have this rule:

`when telegram received "status" then send text telegram to "ok"`

Pimatic will sent message "ok" to all recipients.

How can I define this rule for only send the response to recipient who sends the message "status" ?

**Comment by SenTzu01** [comment]
Currently this feature is not supported. This is more complicated to implement as it may seem at a first glance. I may give it consideration when I work on a future release which has not been planned yet.

**Comment by SenTzu01** [comment]
Feature implementation in progress

**Comment by SenTzu01** [comment]
Version 1.1.9 implements the rule syntax:
when telegram received "..." then send [text | ...] telegram to sender "..."

'sender' is a placeholder for the user sending the command identified in the predicate, and get resolved to the actual user upon action execution. '...to sender' can therefore only be used in combination with a 'telegram received' predicate
