### ISSUE TITLE
Error sending message

### ISSUE THREAD

**Issue by sweebee** [SenTzu01/pimatic-telegram#41]
since today I get this message:

```
error [pimatic-telegram]: [BotClient] Error: Message was NOT sent to all recipients
15:18:00error [pimatic-telegram]: [Message] Sending Telegram "test" to Wiebe: failed; reason: undefined
```

**Comment by sweebee** [comment]
Also found this in the log;

```15:29:00.438 [pimatic-telegram] info: [TypeError: tls.convertNPNProtocols is not a function]```

**Comment by SenTzu01** [comment]
@sweebee can you post the rule action so I can attempt to reproduce? The log entry got me baffled, this must be somewhere in the dependency chain....

**Comment by SenTzu01** [comment]
Any chance this issue is the same as: https://github.com/pimatic/pimatic/issues/1099 ?

**Comment by sweebee** [comment]
Yes the same issue, so not related to this plug-in.
