### ISSUE TITLE
Regulary no reaction 

### ISSUE THREAD

**Issue by sclaren** [SenTzu01/pimatic-telegram#44]
At least one a day I need to restart the listener by editing the telegram device in Pimatic in order to keep in working. Every Morning I send a message through the bot to my Pimatic instance, the plugin does nothing until it was restarted. There is no debug output. Pimatic itself works without any issues

**Comment by Daubsen** [comment]
Had the same problem. Everytime the ISP provieds a new IP to your Router the receiver won't answer. Preventing the IP reset solved it for me. Hope this helps.

**Comment by SenTzu01** [comment]
Issue is not caused by the plugin.

**Comment by SenTzu01** [comment]
Have implemented a "reload <TelegramReceiverDevice> action for the rule engine in Alpha . This may provide somewhat of a workaround.
