### ISSUE TITLE
Currently my Telegram Plugin isnt working anymore. See this Stacktrace

### ISSUE THREAD

**Issue by scobby** [SenTzu01/pimatic-telegram#47]
Service just stopped working and after a reboot i see this in pimatic.log:

Can you help?

23:23:48.223 [pimatic] Installing: "pimatic-telegram@1.1.14" from npm-registry.
23:23:52.767 [pimatic, ppm] WARN engine pimatic-telegram@1.1.14: wanted: {"node":">=8.0.0","npm":">1.1.x"} (current: {"node":"4.6.2","npm":"2.15.12"})
23:23:53.751 [pimatic, ppm] WARN engine telegraf@3.34.1: wanted: {"node":">=8"} (current: {"node":"4.6.2","npm":"2.15.12"})
23:24:15.485 [pimatic, ppm] pimatic-telegram@1.1.14 node_modules/pimatic-telegram
23:24:15.488 [pimatic, ppm] ├── pimatic-plugin-commons@0.8.8
23:24:15.491 [pimatic, ppm] └── telegraf@3.34.1 (module-alias@2.2.2, telegram-typings@3.6.1, sandwich-stream@2.0.2, node-fetch@2.6.0, minimist@1.2.0, debug@4.1.1, @types/node@12.12.14)
23:24:15.548 [pimatic] Loading plugin: "pimatic-telegram" (1.1.14)
coffee-cache: compiling coffee-script file "telegram.coffee"...Done
23:24:20.649 [pimatic] Unexpected token {
23:24:20.722 [pimatic] SyntaxError: Unexpected token {
23:24:20.722 [pimatic]>    at exports.runInThisContext (vm.js:53:16)
23:24:20.722 [pimatic]>    at Module._compile (module.js:373:25)
23:24:20.722 [pimatic]>    at Object.Module._extensions..js (module.js:416:10)
23:24:20.722 [pimatic]>    at Module.load (/home/pi/pimatic-app/node_modules/pimatic-mobile-frontend/node_modules/nap/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
23:24:20.722 [pimatic]>    at Function.Module._load (module.js:300:12)
23:24:20.722 [pimatic]>    at Module.require (module.js:353:17)
23:24:20.722 [pimatic]>    at require (internal/module.js:12:17)
23:24:20.722 [pimatic]>    at module.exports (/home/pi/pimatic-app/node_modules/pimatic-telegram/telegram.coffee:14:17)
23:24:20.722 [pimatic]>    at PluginManager.loadPlugin (/home/pi/pimatic-app/node_modules/pimatic/lib/plugins.coffee:84:16)
23:24:20.722 [pimatic]>    at /home/pi/pimatic-app/node_modules/pimatic/lib/plugins.coffee:492:25
23:24:20.722 [pimatic]>    at tryCatcher (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/util.js:26:23)
23:24:20.722 [pimatic]>    at Promise._settlePromiseFromHandler (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:510:31)
23:24:20.722 [pimatic]>    at Promise._settlePromiseAt (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/promise.js:584:18)
23:24:20.722 [pimatic]>    at Async._drainQueue (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/async.js:128:12)
23:24:20.722 [pimatic]>    at Async._drainQueues (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/async.js:133:10)
23:24:20.722 [pimatic]>    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/pimatic-app/node_modules/pimatic/node_modules/request-promise/node_modules/bluebird/js/main/async.js:15:14)
23:24:20.722 [pimatic]>    at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by SenTzu01** [comment]
You have an incompatible node version. Not a bug.

**Comment by scobby** [comment]
ok, didnt saw this. thx for the help.

**Comment by SenTzu01** [comment]
I replied to your post on the pimatic forum with some hints to revert to a previous version
