### ISSUE TITLE
feature request: automatic send retry

### ISSUE THREAD

**Issue by manolitto** [SenTzu01/pimatic-telegram#49]
pimatic-telegram is great, thank you!
I use it to get notified of nearly everything thats happening in my "smart" home. And I use pimatic also to monitor my WLAN, my internet connection, modem state, etc. And the telegram client would send me alert messages to my smartphone if there are networking issues. Well it "would"... you can guess ;-)
Of course, pimatic-telegram plugin cannot do the magic of sending messages without internet connection. :-) But, what would be of great help (and a cool feature): If the telegram client would have some kind of automatic retry mechanism.
Let's say it automatically retries to send messages twice: after 1 minute and again after 15 minutes or so. Perhaps even configurable?
Currently, even if there is only a short network connection outage, a corresponding telegram alert message would never receive any recipient. Automatic retries would help a lot to get notified after such short outages or during unstable network conditions.
WDYT?

**Comment by SenTzu01** [comment]
Hi Manolitto,

I think I understand your use-case. However, monitoring the network is out of scope for pimatic-telegram functionality.
It would be better if a separate pimatic plugin would be available that checks the availability of your LAN and internet connection.
Based on status Pimatic could then alert you on events using pimatic-telegram or other communication plugins.
